== What is a service?

The process you interacted with in the previous step was a foreground
process. It ran in a terminal window where you could see it. Some
processes run in the background, out of view of the user. These
background processes allow the system to carry out many operations in
parallel. Background processes that continuously carry out a set of
actions are called _services_.

_Daemons_ are even more specialized. These are services that and are
specifically designed to supervise or support other processes.
Typically, daemons are denoted by a *d* at the end of their name. For
example, *firewalld* is the daemon which handles firewall functionality.
These daemons lie in wait, listening for the user to issue a command to
tell them to change their behavior.

== Viewing the status of a service

*firewalld* is a service which manages what network traffic to let into
the system. Check the status of the *firewalld* service with the
following command:

[source,bash,run]
----
systemctl status firewalld.service --no-pager
----

From this status message it is clear that the *firewalld* service is
installed and active. But what is managing this service? It turns out
that another service, *systemd*, is in charge of managing all of the
services on the system.

== systemd vs. systemctl

When researching service management, you will come across two very
similar terms: *systemd* and *systemctl*. These are very closely
related. *systemd*, short for system daemon, manages the state of the
system and any services running on it. Since *systemd* is a daemon, it
runs in the background and needs a set of commands for users to interact
with it. *systemctl* provides these commands. The `+systemctl status+`
command above is one example of this, and the upcoming steps will walk
you through starting and enabling a service with *systemctl*.
