---
virtualmachines:
  - name: "rhel"
    image: "rhel-10-0-07-09-25-3"
    bootloader: efi
    cores: 1
    memory: "4G"
    image_size: "40G"
    packages:
      - nfs-utils
      - rpcbind
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
    services:
      - name: node02-http
        ports:
          - port: 80
            protocol: TCP
            targetPort: 80
            name: node02
    routes:
      - name: node02-web
        host: node02
        service: node02-http
        targetPort: 80
