---
virtualmachines:
  - name: "rhel"
    image: "rhel-10-0-07-09-25-3"
    bootloader: efi
    cores: 1
    image_size: "40G"
    packages:
      - nfs-utils
      - rpcbind
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
